### ISSUE TITLE
Error:(32, 10) fatal error: 'config.h' file not found

### ISSUE THREAD

**Issue by fantomFire** [alidili/FFmpeg4Android#2]
C:\Users\win7-64\myPhoto\app\src\main\cpp\ffmpeg.c Error:(32, 10) fatal error: 'config.h' file not found
博主 把你的项目抄过来 这个文件找不见

**Comment by alidili** [comment]
config.h在这里https://github.com/alidili/FFmpeg4Android/tree/master/ffmpeg-3.4.2

**Comment by fantomFire** [comment]
能留个联系方式么 有些地方还是有问题 QQ416933316

**Comment by alidili** [comment]
2803439906
